name: Deploy to OCI Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USERNAME }}
        key: ${{ secrets.OCI_SSH_KEY }}
        script: |
          cd /var/www/2ul.top
          ls -la
          echo $PATH
          yarn --version
          node --version
          yarn install --frozen-lockfile
          yarn build
