name: Deploy to OCI Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_HOST }}
        username: ${{ secrets.OCI_USERNAME }}
        key: ${{ secrets.OCI_SSH_KEY }}
        script: |
          echo "Sourcing NVM"
          source ~/.nvm/nvm.sh
          echo "Changing directory to /var/www/2ul.top"
          cd /var/www/2ul.top
          echo "Checking Yarn version"
          yarn --version
          echo "Checking Node version"
          node --version
          echo "Installing dependencies"
          yarn install --frozen-lockfile
          echo "Building the project"
          yarn build
